{% set name = "ai4s-jobq" %}
{% set version = "2.16.2" %}
{% set suffix = ".post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4cbf6ed68ea28205358663dd14a30e08d5d0406a9e0198df16cf222e93b86624

build:
  entry_points:
    - ai4s-jobq = ai4s.jobq.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=35.0.2
    - setuptools-scm >=8
    - wheel >=0.29.0
  run:
    - aiohttp
    - anyio
    - appdirs
    - asyncclick <8.2.2
    - azure-identity
    - azure-monitor-opentelemetry
    - azure-servicebus
    - azure-storage-blob
    - azure-storage-queue
    - cachetools
    - joblib
    - psutil
    - python >={{ python_min }}
    - pyyaml
    - rich
    - types-python-dateutil

test:
  imports:
    - ai4s
  commands:
    - pip check
    - ai4s-jobq --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aka.ms/jobq
  dev_url: https://github.com/microsoft/ai4s-jobq
  doc_url: https://microsoft.github.io/ai4s-jobq/
  summary: AI for Science Job Queue - A distributed job queue system for large scale embarassingly parallel workloads
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
